import os
from pathlib import Path

from setuptools import setup, find_packages
from torch.utils.cpp_extension import (
    BuildExtension, CUDAExtension, CppExtension, CUDA_HOME
)


ROOT = Path(__file__).parent
INCLUDE_DIR = str((ROOT / 'src' / 'toast' / 'include').absolute())

CUDA_EXTRA_ARGS = {
    "cxx": [
        "-fvisibility=hidden",
        '-DAT_PARALLEL_OPENMP',
        '-fopenmp', '-O3',
        '-DTOAST_WITH_CUDA'
    ],
    "nvcc": [
        "-DCUDA_HAS_FP16=1",
        "-D__CUDA_NO_HALF_OPERATORS__",
        "-D__CUDA_NO_HALF_CONVERSIONS__",
        "-D__CUDA_NO_HALF2_OPERATORS__",
        "--extended-lambda",
        "-O3",
        '-DAT_PARALLEL_OPENMP',
        "-Xcompiler", "-fopenmp"
    ]
}

CPU_EXTRA_ARGS = {
    "cxx": ["-fvisibility=hidden", '-DAT_PARALLEL_OPENMP', '-fopenmp', '-O3'],
}


def find_sources(path):
    path = Path(path)
    return list(filter(lambda x: ('cmake-' not in x), map(str,
        list(path.rglob('*.cpp')) + list(path.rglob('*.cu'))
    )))


def build_with_cuda() -> bool:
    # Decide whether to build the CUDA kernels.

    if os.environ.get('TOAST_CPU_ONLY', '0') == '1':
        return False
    if os.environ.get('TOAST_FORCE_CUDA', '0') == '1':
        return True
    if CUDA_HOME is None:
        return False

    nvcc = Path(CUDA_HOME, 'bin', 'nvcc.exe' if os.name == 'nt' else 'nvcc')
    return nvcc.exists()


def cpu_only_sources():
    # When build is CPU-only, g++ does not recognize .cu files as compilable sources
    # current hack: generate .cpp files which include original cu files
    cpp_shim_dir = ROOT / 'build' / 'cpu_sources'
    csrc_dir = ROOT / 'csrc'

    cpp_shim_dir.mkdir(parents=True, exist_ok=True)
    sources = [
        str(p) for p in sorted(csrc_dir.rglob('*.cpp'))
        if 'cmake-' not in str(p)
    ]

    for cu in sorted(csrc_dir.rglob('*.cu')):
        if 'cmake-' in str(cu):
            continue
        shim = cpp_shim_dir / (cu.stem + '.cpp')
        content = (
                '// Generated by setup.py for the CPU-only build.\n'
                '#include "%s"\n' % cu.absolute()
        )

        if not shim.exists() or shim.read_text() != content:
            shim.write_text(content)

        sources.append(str(shim))

    return sources


if build_with_cuda():
    print('pytoast: building WITH CUDA (CUDA_HOME=%s)' % CUDA_HOME)
    ext_modules = [
        CUDAExtension(
            'toast._C',
            sources=find_sources('csrc'),
            include_dirs=[INCLUDE_DIR],
            extra_compile_args=CUDA_EXTRA_ARGS,
        )
    ]
else:
    print('pytoast: building CPU-ONLY (no usable CUDA toolkit found).\n'
          '         CUDA operations will be unavailable; the fused CPU kernels\n'
          '         are built as usual. Set TOAST_FORCE_CUDA=1 if this is wrong.')
    ext_modules = [
        CppExtension(
            'toast._C',
            sources=cpu_only_sources(),
            include_dirs=[INCLUDE_DIR],
            extra_compile_args=CPU_EXTRA_ARGS,
            extra_link_args=['-fopenmp'],
        )
    ]


setup(
    name='pytoast',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    package_data={'toast': ['include/**/*.h']},
    ext_modules=ext_modules,
    cmdclass={
        'build_ext': BuildExtension
    },
    version="0.2.0",
)
